// @ts-expect-error `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
import { default as handler } from "./.open-next/worker.js";
import type { CloudflareBindings } from "./src/lib/db";
import { runPriceSync } from "./src/lib/price-sync/run";
import { steamPriceProvider } from "./src/lib/price-sync/steam-provider";

function numberVar(value: string | undefined, fallback: number) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}

export default {
  fetch: handler.fetch,
  async scheduled(_event, env, ctx) {
    ctx.waitUntil(
      runPriceSync(steamPriceProvider, {
        database: env.DB,
        maxItems: numberVar(env.PRICE_SYNC_BATCH_SIZE, 8),
        delayMs: numberVar(env.PRICE_SYNC_DELAY_MS, 1200)
      })
    );
  }
} satisfies ExportedHandler<CloudflareBindings>;
